### ISSUE TITLE
Label Text only replaces first instance of Underscore

### ISSUE THREAD

**Issue by SlashmanX** [GothAck/forms-mongoose#3]
The functionality of this plugin is setup so underscores are replaced by spaces, however this only works on the first occurrence of an underscore die to the limitations of Javascript's `replace` method.

To fix, simply change line 53 in fields.js to:

`label = name[0].toUpperCase() + name.substr(1).replace(/_/g, ' ');`

P.S. If you want me to submit this and #2 as pull requests that's no problem, it's just the problems I've found are simply 1 line fixes

EDIT: Just realised that fields.js is in an external node_module and can't exactly be fixed by you. My bad

**Comment by GothAck** [comment]
Haha, thanks dude, got very confused there :P Probably best you submit that to https://github.com/caolan/forms :D
